### ISSUE TITLE
(Bug) Transparent Material Issues

### ISSUE THREAD

**Issue by Korikan** [kirides/GD3D11#92]
Transparent Materials arent Rendered correctly, they have Transparency and Light Issues.

(Original)
https://i.ibb.co/7SdNR5p/image-2021-12-20-023945.png

(Renderer)
https://i.ibb.co/sWbGFY1/image-2021-12-20-023829.png

**Comment by Korikan** [comment]
I managed to figure out what exactly the issue is, the Renderer seems to struggle with double sided faces that have a solid Texture assigned but are transparent due to the assigned Material properties, therefore casting shadows on each other. The Issue can be avoided by making sure that the faces arent double sided.

**Comment by kirides** [comment]
Fixed in the next nightly.
causes were:
1. incorrectly collected meshes, by invalid mesh comparator, causing "ice" and "ground" to be the same.
2. "NONE"-culling causes incorrectly lit ice-ground and likely more.

**Comment by stefson** [comment]
what means next nightly? do you prepare another commit on top of current nightly at the moment, which will close this issue?

**Comment by kirides** [comment]
@stefson 

#358 will close this issue in particular.

The implementation MAY have caused other issues, but i did not see any in a quick run through the few areas and effects.

**Comment by stefson** [comment]
the frozen river on the other side of the frozen lake has some very funny artefacts since 2023, last time I checked in January(?) 2026 it was still present: 

<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/880554bf-2b5e-42a9-92bd-021a9a043b8d" />

**Comment by kirides** [comment]
https://github.com/kirides/GD3D11/commit/3f5a86b29f580d7e8add236f84a6a56adb562445

Nightly is up.

Frozen lake and likely other accidentally miss-classified world mesh items are now rendered more akin to how it's done in original games. Not 100% same, but looked good enough at day and night for a first take.
